### ISSUE TITLE
The `install_plugins` capability requirements break the plugin on Multisite with file write restriction environments

### ISSUE THREAD

**Issue by piotr-bajer** [itteco/iframely-wordpress#41]
Hi,

I noticed in these lines:

https://github.com/itteco/iframely-wordpress/blob/d3255e4717315206482961e796f5db4484695df7/app/UI/Settings.php#L30
https://github.com/itteco/iframely-wordpress/blob/d3255e4717315206482961e796f5db4484695df7/app/UI/Settings.php#L65

you used the `install_plugins` capability for Multisite WP instances to check if the user has permission for certain actions. 

If the `wp_is_file_mod_allowed` returns `false` (the file modification is not allowed through constant `DISALLOW_FILE_MODS` or `file_mod_allowed` filter), the plugin's settings page will not show up on such instances and there will be no way to save API key. 

We are building a site on WP VIP hosting which has these restrictions, and we cannot use this plugin without a workaround.

Is it possible to change these capabilities to `manage_options` or add a filter to customize them?

For the context, the WP core checks if the files are writable and returns false for the `install_plugins` capability check here:
https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L615-L627

**Comment by yellowby** [comment]
Hi @piotr-bajer 

We have updated the plugin and lowered the capability requirements for multisite to `manage_network_options`. I hope this helps.
