### ISSUE TITLE
The plugin does not work on WP 6.3.2 and 6.4.1

### ISSUE THREAD

**Issue by piotr-bajer** [itteco/iframely-wordpress#42]
Hi,

I have tested the latest version of your WordPress plugin on WP 6.3.2 and 6.41 and it does not seem to work.

- In 6.3.2 observed the following issues:
  - The Iframely options in the block uncheck themselves randomly:
  
  https://github.com/itteco/iframely-wordpress/assets/12783610/1a702da7-9fcb-426a-886d-e701d78f5068
  
  - When you check Iframley option and save the post, then reload the post the embed block causes parsing error:
  ![image](https://github.com/itteco/iframely-wordpress/assets/12783610/df5a5d25-a507-4c58-81cf-6fcaa3c012e4)
  The console reports:
  ```
  blocks.min.js?ver=b5d3b99262dfb659bd26:10 Block validation: Block validation failed for `core/embed` (Object).

  Content generated by `save` function:

  <figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block- 
  embed__wrapper">
  https://www.youtube.com/watch?v=84wL7JOar8wu0026iframely=eyJjbGlja190b19wbGF5Ijp0cnVlfQ%3D%3D
  </div></figure>

  Content retrieved from post body:

  <figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube"><div class="wp-block- embed__wrapper">
  https://www.youtube.com/watch?v=84wL7JOar8w&iframely=eyJjbGlja190b19wbGF5Ijp0cnVlfQ%3D%3D
  </div></figure>
  ```
- In 6.4.1 the embed block crashes once you enter the URL:

https://github.com/itteco/iframely-wordpress/assets/12783610/e8243596-34a8-4022-af4c-f24aca330e2c

The console reports the following error:
```
TypeError: Cannot read properties of null (reading 'innerHTML')
    at c.updateEmptyPlaceholder (index.js?ver=1.0.2:1:1175)
    at c.componentDidMount (index.js?ver=1.0.2:1:1690)
    at Jr (react-dom.min.js?ver=18.2.0:10:80714)
    at Zr (react-dom.min.js?ver=18.2.0:10:80489)
    at Gr (react-dom.min.js?ver=18.2.0:10:80023)
    at react-dom.min.js?ver=18.2.0:10:91526
    at xl (react-dom.min.js?ver=18.2.0:10:92039)
    at fl (react-dom.min.js?ver=18.2.0:10:85808)
    at Nn (react-dom.min.js?ver=18.2.0:10:32474)
    at react-dom.min.js?ver=18.2.0:10:83226
```
This leads to this line in the current version of the plugin https://github.com/itteco/iframely-wordpress/blob/main/src/js/components/IframelyOptions.js#L16C1-L16C1 which does not check if the element exists (the `placeholder` element is null sometimes).

Could you look into these errors?

**Comment by yellowby** [comment]
@piotr-bajer Thank you for reporting the issue. The plugin is now compatible with the latest WordPress versions.
