### ISSUE TITLE
The 'install_plugins' capability check prevents from saving settigns on multisite instances when file editing is disabled

### ISSUE THREAD

**Issue by piotr-bajer** [itteco/iframely-wordpress#44]
Hi,

Thanks for fixing the issue in https://github.com/itteco/iframely-wordpress/issues/41, but there is one more place where the `install_plugins` capability is used for multisite instances, could you also change the capability to `manage_network_options` here:

https://github.com/itteco/iframely-wordpress/blob/eb9998405bbe024f508c94b7002b4b4d0cb18011/app/UI/Settings.php#L71C1-L71C1

This prevents from saving the settings on save there is not enough permissions screen.

Thanks,
Piotr

**Comment by yellowby** [comment]
Hi @piotr-bajer,

Once again, thank you for reporting the issue. 
We updated the plugin, so it should be fine now.
